name: flutter_native_ml
description: A Flutter plugin that gives direct access to device-native machine learning accelerators like the Apple Neural Engine and Android NNAPI for blazing-fast on-device inference.
version: 1.0.0
homepage: https://github.com/your_repo/flutter_native_ml # Your repo link here

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_native_ml
        pluginClass: FlutterNativeMlPlugin
        kotlinPlugin: "yes"
      ios:
        pluginClass: FlutterNativeMlPlugin