name: flutter_native_ml_builder
description: A command-line utility to convert and prepare ML models for flutter_native_ml.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  args: ^2.3.1
  process_run: ^0.12.3
  path: ^1.8.2

# To use this, navigate to the `flutter_native_ml` root and run:
# dart run flutter_native_ml_builder:ml_builder --help
executables:
  ml_builder: builder